name: generative_moons

channels:
  - pytorch
  - scikit-learn
  - conda-forge
  - defaults

dependencies:
  - python=3.10
  - pytorch=2.*
  - lightning=2.*
  - torchmetrics=0.*
  - hydra-core=1.*
  - rich=13.*
  - pre-commit=3.*
  - wandb
  - scikit-learn=1.*
  - matplotlib
  - umap-learn
  - plotly
  - pandas

  - pip>=23
  - pip:
      - hydra-optuna-sweeper
      - hydra-colorlog
      - rootutils
