defaults:
  - default

model:
  _target_: torch.nn.Sequential
  _args_:
    - _target_: torch.nn.Sequential
      _args_:
        - _target_: torch.nn.Linear
          in_features: 2
          out_features: 8
        - _target_: torch.nn.ReLU
          inplace: True
        - _target_: torch.nn.Linear
          in_features: 8
          out_features: 4
    - _target_: torch.nn.Sequential
      _args_:
        - _target_: torch.nn.Linear
          in_features: 4
          out_features: 8
        - _target_: torch.nn.ReLU
          inplace: True
        - _target_: torch.nn.Linear
          in_features: 8
          out_features: 2

loss:
  _target_: torch.nn.MSELoss
