defaults:
  - default

model:
  _target_: src.models.components.vae.VAE

  encoder:
    _target_: src.models.components.vae.Encoder

    input_dim: 2
    hidden_dims: 32
    latent_dim: 2

  decoder:
    _target_: src.models.components.vae.Decoder

    input_dim: 2
    hidden_dims: 32
    output_dim: 2

  eps_w: 0.1

loss:
  _target_: src.models.components.vae.VAELoss

  beta: 1.0
  reduction: mean
