defaults:
  - default

model:
  _target_: src.models.components.vae.VAE

  encoder:
    _target_: src.models.components.vae.Encoder

    input_dim: 2
    hidden_dims: 4
    latent_dim: 8

  decoder:
    _target_: src.models.components.vae.Decoder

    input_dim: ${model.model.encoder.latent_dim}
    hidden_dims: 4
    output_dim: ${model.model.encoder.input_dim}

  eps_w: 0.1

loss:
  _target_: src.models.components.vae.VAELoss

  beta: 1.0
  reduction: mean
